#!/bin/bash
sudo update-alternatives --set java /home/jiengfei/programs/jdk1.6.0_45/bin/java
sudo update-alternatives --set javac /home/jiengfei/programs/jdk1.6.0_45/bin/javac
sudo update-alternatives --set javaws /home/jiengfei/programs/jdk1.6.0_45/bin/javaws
sudo update-alternatives --set jar /home/jiengfei/programs/jdk1.6.0_45/bin/jar
